spring:
  application:
    name: QuizServer

  datasource:
    url: jdbc:h2:file:./data/quizdb
    driver-class-name: org.h2.Driver
    username: admin
    password: pass1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

server:
  port: 8080

app:
  jwt:
    secret: "my-super-secret-key-for-famous-quote-quiz-server-2026-secure-key"
    expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG